spring.application.name=testWeb
server.servlet.context-path=/api
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgresql_test
spring.datasource.username=postgres
spring.datasource.password=postgres
logging.level.com.example=INFO

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG

jwt.secret=your-256-bit-secret-your-256-bit-secret
# Token expiration time in minutes
jwt.expiration=3
###################################
# message propaties
###################################
spring.messages.basename=messages
spring.messages.encoding=UTF-8
